package com.haidie.gridmember.mvp.bean

import com.google.gson.annotations.SerializedName

/**
 * Create by   Administrator
 *      on     2018/12/18 14:09
 * description
 */
data class PersonalInfoData(
    val id: Int,
    val admin_id: Int,
    val area_id: Int,
    val name: String,
    val nickname: Any,
    val gender: String,
    val avatar: String?,
    val identity: String,
    val birthday: String,
    val phone: String,
    val nationality: String,
    val house_relation: String?,
    val live_address_type: String,
    val register_address_province: String,
    val register_address_city: String,
    val register_address_area: String,
    val live_address_province: String,
    val live_address_city: String,
    val live_address_area: String,
    val house_id: Int,
    val marriage_status: String?,
    val religion: String?,
    val education: String,
    val company: String,
    val job: String?,
    val special_skills: String?,
    val politics_status: String,
    val entry_party_time: String,
    val org_relation_address_province: String?,
    val org_relation_address_city: String?,
    val org_relation_address_area: String?,
    val org_relation_address: String,
    val commend_status: String?,
    val is_children: Int,
    val school: String,
    val grade: String,
    @SerializedName("class")
    val clazz: String,
    val student_special_skills: String?,
    val student_hobby: String?,
    val student_character: String,
    val student_score: String?,
    val student_good_subject: String?,
    val student_bad_subject: String?,
    val is_single_parent: String,
    val is_allergy: String,
    val family_information: String?,
    val is_problem_youth: Int,
    val is_problem_youth_type: String?,
    val is_empty_nester_elder: Int,
    val is_disease_patients: Int,
    val is_disease_patients_type: String?,
    val is_voman: Int,
    val is_voman_disease_type: Int?,
    val is_voman_disease_category: Int?,
    val is_voman_name: String?,
    val is_voman_category: String?,
    val is_difficult_masses: Int,
    val is_difficult_masses_type: String?,
    val is_difficult_masses_reason: String?,
    val is_difficult_masses_out_time: String,
    val is_unemployed_person: Int,
    val is_disabled_person: Int,
    val is_disabled_person_type: String?,
    val is_disabled_person_rank: String?,
    val is_mental_retardation_person: Int,
    val is_mental_retardation_rank: String?,
    val is_party_members: Int,
    val is_military_strength: Int,
    val family_income_source: String?,
    val family_income: Int,
    val family_wage_income: Int,
    val family_operational_income: Int,
    val family_low_income: Int,
    val family_pension_income: Int,
    val family_area_num: Int,
    val family_person_num: Int,
    val family_area_time: String,
    val family_area_flow_num: Int,
    val is_enter_baseic_old_insurance: String,
    val is_enter_baseic_medical_insurance: String,
    val is_enter_new_insurance: String,
    val help_info: String?,
    val vehicle_type: List<VehicleType>,
    val create_time: Any,
    val update_time: Any,
    val delete_tag: Int) {
    data class VehicleType(
        val id: Int,
        val vehicle_type: String?,
        val lecense_id: String?,
        val engine_id: String?,
        val motor_id: String?,
        val color: String)
}